Update komb.py
Line 328: Failure to decode here seems to break function.

  File "", line 330, in callMetagenomePipeline
    num_reads = int(p.split(' ')[0])/4
TypeError: a bytes-like object is required, not 'str'
 Which traces back to decode problem in line 328. Coercion of p into int doesn't quite work 

https://stackoverflow.com/questions/33054527/typeerror-a-bytes-like-object-is-required-not-str-when-writing-to-a-file-in
Former-commit-id: 77c58ebb59af99d8166b8bd2106e4ba9da2bd221